# Monitor
monitor = , preferred, auto, 1

# NVIDIA environment variables
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

# Autostart
exec-once = waybar
exec-once = dunst

# Modifier
$mod = SUPER

# Keybindings
bind = $mod, Q, exec, kitty
bind = $mod, C, killactive
bind = $mod, M, exit
bind = $mod, R, exec, rofi -show drun
bind = $mod, B, exec, zen-browser

# Switch workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4

# Move active window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
